version: "3.9"
services:
    #    mysql:
    #        container_name: mysql8
    #        image: mysql:8
    #        restart: always
    #        environment:
    #            MYSQL_ROOT_HOST: "%"
    #            MYSQL_DATABASE: "db"
    #            MYSQL_ROOT_PASSWORD: root123
    #            MYSQL_USERNAME: app
    #            MYSQL_PASSWORD: app123
    #            TZ: Asia/Seoul
    #        volumes:
    #            - mysql:/var/run/mysqld
    #        ports:
    #            - 3306:3306
    #        networks:
    #            - app
    #        healthcheck:
    #            test: "/usr/bin/mysql --user=root --password=root--execute \"SHOW DATABASES;\""
    #            interval: 2s
    #            timeout: 20s
    #            retries: 10
    #        command:
    #            - --default-authentication-plugin=mysql_native_password
    #            - --character-set-server=utf8mb4
    #            - --collation-server=utf8mb4_unicode_ci
    #            - --range_optimizer_max_mem_size=16777216
    redis:
        container_name: weproud-redis
        image: redis:latest
        restart: always
        volumes:
            - redis:/data
        ports:
            - "6379:6379"
        labels:
            - "name=redis"
            - "mode=standalone"
        networks:
            - app
        #    command: redis-server --requirepass changeme --port 6379
        command: redis-server --port 6379

    localstack:
        image: localstack/localstack:1.4.0-arm64
        container_name: weproud-localstack
        ports:
            - "4510-4559:4510-4559"  # external service port range
            - "4566:4566"            # LocalStack Edge Proxy
        environment:
            - SERVICES=sns,sqs   # 사용할 서비스 목록
            - DEBUG=${DEBUG-}
            - DATA_DIR=${DATA_DIR-}
            - HOST_TMP_FOLDER=${TMPDIR:-/tmp/}localstack
            - DOCKER_HOST=unix:///var/run/docker.sock
            - AWS_ACCESS_KEY_ID=test
            - AWS_SECRET_ACCESS_KEY=test
            - AWS_DEFAULT_REGION=us-east-1
            - DEFAULT_REGION=us-east-1
        volumes:
            - "${TMPDIR:-/tmp}/localstack:/var/lib/localstack"
            - "./etc/localstack/init/ready.d:/etc/localstack/init/ready.d"

volumes:
    #    mysql:
    redis:
    localstack:

networks:
    app:
        driver: bridge
